os: linux
dist: xenial
language: python
cache: pip

python:
  - "3.6"
  - "3.7"

install:
  - pip install $(cat requirements-test.txt)
  - pip install .

script:
  - export PYTHONPATH=src/:$PYTHONPATH
  - export MYPYPATH=stubs/
  - python -m flake8 src/lib3to6/
  - python -m mypy src/lib3to6/
  - python -m pytest --cov=lib3to6 test/
  - rst2html5 --strict README.rst > /dev/null
