os: linux
dist: xenial
sudo: true

language: python
cache: pip

python:
  - "3.6"
  - "3.7"

install:
  - python -m pip install $(cat requirements-test.txt)
  - python -m pip install .
  - python setup.py bdist_wheel --python-tag=py2.py3

script:
  - python -m flake8 src/lib3to6/
  - export MYPYPATH=stubs/
  - python -m mypy src/lib3to6/

  # first test module from installed wheel
  - python -m pip uninstall -y lib3to6
  - python -m pip install $(ls -1t dist/lib3to6*.whl | head -n 1)
  - grep "coding: utf-8" $(python -c "import lib3to6;print(lib3to6.__file__)")
  - python -m pytest test/

  # next test module from src/
  - export PYTHONPATH=src/:$PYTHONPATH
  - grep "coding: utf-8" $(python -c "import lib3to6;print(lib3to6.__file__)") || exit 1
  - python -m pytest --cov=lib3to6 test/

  - rst2html5 --strict README.rst > /dev/null
  - rst2html5 --strict CHANGELOG.rst > /dev/null
